// <auto-generated />
using System;
using CenitStoryTeller.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CenitStoryTeller.Data.Migrations
{
    [DbContext(typeof(NovelaDbContext))]
    [Migration("20260607020050_AddConfiguracionLlm")]
    partial class AddConfiguracionLlm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Beat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Funcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Orden");

                    b.ToTable("Beats");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Capitulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BeatObjetivoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Plataforma")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("BeatObjetivoId");

                    b.HasIndex("ObraId", "Orden");

                    b.ToTable("Capitulos");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.CapituloVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CapituloId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PromptUsado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CapituloId", "NumeroVersion")
                        .IsUnique();

                    b.ToTable("CapituloVersiones");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CambioConsecuencia")
                        .HasColumnType("text");

                    b.Property<string>("MomentoInWorld")
                        .HasColumnType("text");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Orden");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EliminadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Intake")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logline")
                        .HasColumnType("text");

                    b.Property<string>("Medio")
                        .HasColumnType("text");

                    b.Property<string>("PlataformaObjetivo")
                        .HasColumnType("text");

                    b.Property<string>("TemaCentral")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UniversoCompartido")
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Personaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arquetipo")
                        .HasColumnType("text");

                    b.Property<string>("Canon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Deseo")
                        .HasColumnType("text");

                    b.Property<string>("EstadoEnTrama")
                        .HasColumnType("text");

                    b.Property<string>("EstadoVital")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeridaCentral")
                        .HasColumnType("text");

                    b.Property<string>("Necesidad")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Restricciones")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Nombre");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.PruebaAcido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ambiental")
                        .HasColumnType("boolean");

                    b.Property<bool>("Anacronismo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CapituloVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FidelidadFuncional")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fisica")
                        .HasColumnType("boolean");

                    b.Property<string>("Hallazgos")
                        .HasColumnType("text");

                    b.Property<string>("Parches")
                        .HasColumnType("text");

                    b.Property<bool>("Psicologica")
                        .HasColumnType("boolean");

                    b.Property<bool>("Quimica")
                        .HasColumnType("boolean");

                    b.Property<string>("Veredicto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CapituloVersionId")
                        .IsUnique();

                    b.ToTable("PruebasAcido");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.RegistroPaso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Agente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Cambios")
                        .HasColumnType("text");

                    b.Property<string>("CanonSnapshot")
                        .HasColumnType("text");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Timestamp");

                    b.ToTable("RegistrosPaso");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Ubicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Canon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoActual")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<string>("RolEnTrama")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Nombre");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("CenitStoryTeller.Data.Entities.ConfiguracionLlm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModelDraft")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ModelReview")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesLlm");
                });

            modelBuilder.Entity("CenitStoryTeller.Data.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreDisplay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EventoPersonaje", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonajesId")
                        .HasColumnType("uuid");

                    b.HasKey("EventoId", "PersonajesId");

                    b.HasIndex("PersonajesId");

                    b.ToTable("EventoPersonaje", (string)null);
                });

            modelBuilder.Entity("EventoUbicacion", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UbicacionesId")
                        .HasColumnType("uuid");

                    b.HasKey("EventoId", "UbicacionesId");

                    b.HasIndex("UbicacionesId");

                    b.ToTable("EventoUbicacion", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Beat", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Obra", null)
                        .WithMany("Beats")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Capitulo", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Beat", null)
                        .WithMany()
                        .HasForeignKey("BeatObjetivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CenitStoryTeller.Core.Entities.Obra", null)
                        .WithMany("Capitulos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.CapituloVersion", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Capitulo", "Capitulo")
                        .WithMany("Versiones")
                        .HasForeignKey("CapituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capitulo");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Evento", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Obra", null)
                        .WithMany("Eventos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Personaje", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Obra", null)
                        .WithMany("Personajes")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.PruebaAcido", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.CapituloVersion", null)
                        .WithOne("Acido")
                        .HasForeignKey("CenitStoryTeller.Core.Entities.PruebaAcido", "CapituloVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.RegistroPaso", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Obra", null)
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Ubicacion", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Obra", null)
                        .WithMany("Ubicaciones")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Data.Entities.ConfiguracionLlm", b =>
                {
                    b.HasOne("CenitStoryTeller.Data.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("CenitStoryTeller.Data.Entities.ConfiguracionLlm", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoPersonaje", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CenitStoryTeller.Core.Entities.Personaje", null)
                        .WithMany()
                        .HasForeignKey("PersonajesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoUbicacion", b =>
                {
                    b.HasOne("CenitStoryTeller.Core.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CenitStoryTeller.Core.Entities.Ubicacion", null)
                        .WithMany()
                        .HasForeignKey("UbicacionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CenitStoryTeller.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CenitStoryTeller.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CenitStoryTeller.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CenitStoryTeller.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Capitulo", b =>
                {
                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.CapituloVersion", b =>
                {
                    b.Navigation("Acido");
                });

            modelBuilder.Entity("CenitStoryTeller.Core.Entities.Obra", b =>
                {
                    b.Navigation("Beats");

                    b.Navigation("Capitulos");

                    b.Navigation("Eventos");

                    b.Navigation("Personajes");

                    b.Navigation("Ubicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
